spring.application.name=gsmShop

# H2
spring.datasource.url=jdbc:h2:file:./data/gsmshopdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=ThisIsTest1!
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# JWT
app.jwt.secret=gsmShop256BitSecretKeyForJwtTokenGeneration2026
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

# PayPal Sandbox
paypal.client-id=YOUR_SANDBOX_CLIENT_ID
paypal.client-secret=YOUR_SANDBOX_CLIENT_SECRET
paypal.base-url=https://api-m.sandbox.paypal.com
